FROM ghcr.io/open-webui/open-webui:v0.11.0@sha256:72c0ba641ba75e7aa52655cb242570906ececd09b1140fb736483038a22b3228
COPY backend/open_webui/routers/openai.py /app/backend/open_webui/routers/openai.py
COPY backend/open_webui/routers/ollama.py /app/backend/open_webui/routers/ollama.py
COPY backend/open_webui/utils/tools.py /app/backend/open_webui/utils/tools.py
